import type { TutorSimulationScenarioSet } from '../tutor-simulation.types';

/** Initial scenario bank: bump `version` when scenarios change (reporting / baselines). */
export const SCENARIO_SET_CORE_V1: TutorSimulationScenarioSet = {
  version: 'core-v1',
  scenarios: [
    {
      id: 'uk-math-fractions-sum',
      title: 'Fraction addition (common denominator)',
      behavior: 'partial_attempt',
      grade: 'Year 6',
      subject: 'Mathematics',
      topic: 'Fractions',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 6',
        grade: 'Year 6',
        currentSubject: 'Mathematics',
        chapter: 'Fractions',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: [
        'Add 1/2 + 1/4. I get confused about the denominator.',
        'So is it 2/4 + 1/4 = 3/4? Is that correct?',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['3/4', 'three'],
        structuredShouldHaveCheck: false,
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['fraction'],
      },
    },
    {
      id: 'uk-math-linear-equation',
      title: 'Simple linear equation',
      behavior: 'standard',
      grade: 'Year 8',
      subject: 'Mathematics',
      topic: 'Equations',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 8',
        grade: 'Year 8',
        currentSubject: 'Mathematics',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: ['Solve 2x + 3 = 13.', 'Show me how to get x step by step.'],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['5'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['x', 'equat'],
      },
    },
    {
      id: 'uk-geometry-rectangle-area',
      title: 'Rectangle area',
      behavior: 'rushing',
      grade: 'Year 4',
      subject: 'Mathematics',
      topic: 'Area',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 4',
        grade: 'Year 4',
        currentSubject: 'Mathematics',
        chapter: 'Geometry',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: ['A rectangle is 3 cm by 4 cm. What is the area?'],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['12'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['area', 'cm'],
      },
    },
    {
      id: 'uk-language-grammar-article',
      title: 'Articles (a / an / the)',
      behavior: 'confused',
      grade: 'Year 6',
      subject: 'English',
      topic: 'Articles',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 6',
        grade: 'Year 6',
        currentSubject: 'English',
        learningMode: 'hints',
        locale: 'en-GB',
      },
      studentTurns: [
        "I don't understand when to use 'a' versus 'the'.",
        'Can you give me a very short example?',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        minStructuredSteps: 1,
        skipAnswerPatterns: true,
        topicKeywordsInResponse: ['example'],
      },
    },
    {
      id: 'uk-physics-units-speed',
      title: 'Units / speed',
      behavior: 'standard',
      grade: 'Year 10',
      subject: 'Physics',
      topic: 'Speed',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 10',
        grade: 'Year 10',
        currentSubject: 'Physics',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: [
        'Distance is 100 m and time is 20 s. What is average speed in m/s?',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['5'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['m/s', 'speed'],
      },
    },
    {
      id: 'uk-math-foundation',
      title: 'Percentages',
      behavior: 'standard',
      grade: 'Year 7',
      subject: 'Mathematics',
      topic: 'Percentages',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 7',
        grade: 'Year 7',
        currentSubject: 'Mathematics',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: ['What is 20% of 150? Show one short step.'],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['30'],
        minStructuredSteps: 1,
        topicKeywordsInResponse: ['30', '%'],
      },
    },
    {
      id: 'uk-integrity-not-just-answer',
      title: 'Student asks for final only',
      behavior: 'answer_only',
      grade: 'Year 9',
      subject: 'Mathematics',
      topic: 'Algebra',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 9',
        grade: 'Year 9',
        currentSubject: 'Mathematics',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: ['Give me only the final answer to 7x = 49 with no explanation.'],
      expectations: {
        minFlowStep: 'TEACH',
        minStructuredSteps: 1,
        skipAnswerPatterns: true,
      },
    },
    {
      id: 'uk-math-wrong-attempt',
      title: 'Wrong attempt then correction',
      behavior: 'wrong_attempt',
      grade: 'Year 7',
      subject: 'Mathematics',
      topic: 'Algebra',
      locale: 'en-GB',
      context: {
        yearGroup: 'Year 7',
        grade: 'Year 7',
        currentSubject: 'Mathematics',
        learningMode: 'full_solution',
        locale: 'en-GB',
      },
      studentTurns: [
        'Simplify 2x + x. I think it is 2x².',
        'OK, so the correct answer is 3x?',
      ],
      expectations: {
        minFlowStep: 'TEACH',
        answerContainsPatterns: ['3x'],
        minStructuredSteps: 1,
      },
    },
  ],
};
